# This file was generated by GoReleaser. DO NOT EDIT.
cask "den" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "077d3fb4f4b96343e2e4c791c2de522357f45f84cd2bd5f2c224b837beadd241"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea8306bda60e76236473f24e4bd16aa5c6ce443960746b5e1e5f0e5f58cd28fb"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d31c3716deb5fcc091db0761cb440912e795667d4c99bf7b85ffee9b09e37836"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "750331df426ebb539b9973efe23df386345bb0c9da525cb15aa3658cf8f1b0d4"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_arm64.tar.gz"
    end
  end

  name "den"
  desc "Spawn and drive sbx microVM sandboxes for multi-project dev environments"
  homepage "https://github.com/PillowPillow/den"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "den"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/den"]
    end
  end

  # No zap stanza required

end
