# This file was generated by GoReleaser. DO NOT EDIT.
cask "den" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "4e81c1c69b9445319ee7c9597fdc796b841b65816bdd7bae61b69f2e9b3e0702"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fd082f5223dca50c6bfffa482618a57e83f7c341d6a513321c8454e0affb49c"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "32291fe9c0ffa60b8d8b6f016a02a7e2bb6cfa90367b61f566aa643f47601a1f"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30e481456805e16e33d1c54fe37bd16c28b0dd2829f6a93c7eb9dbc3c9c5a9f8"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_arm64.tar.gz"
    end
  end

  name "den"
  desc "Spawn and drive sbx microVM sandboxes for multi-project dev environments"
  homepage "https://github.com/PillowPillow/den"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "den"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/den"]
    end
  end

  # No zap stanza required

end
