# This file was generated by GoReleaser. DO NOT EDIT.
cask "den" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "82a905eb195225e7fdd9f2f6fcdfc33a537a4bffd2724fff8b7d4330962c5b87"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31b2cd89df01781db09065fb3f3de39dd3e649e8e1dd52fc4b6c475d0daca7fd"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce4f1033cd220277db3810cac805d12b8ddc1f9344e3ad019615c771dd8782b3"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9cc3c2b8d196e80462c2a48a87b7fd12cc3130e0fe3080afe3d5fd799e3030eb"
      url "https://github.com/PillowPillow/den/releases/download/v#{version}/den_#{version}_linux_arm64.tar.gz"
    end
  end

  name "den"
  desc "Spawn and drive sbx microVM sandboxes for multi-project dev environments"
  homepage "https://github.com/PillowPillow/den"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "den"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/den"]
    end
  end

  # No zap stanza required

end
